### ISSUE TITLE
Completion does not write code after hitting "tab"

### ISSUE THREAD

**Issue by hhuuggoo** [Exafunction/codeium.jupyter#3]
https://www.loom.com/share/c16b931716854c408f131d255a51e934?sid=c064edbb-b155-40c7-982b-aae32b8d4343

After injecting the codeium api token, Jupyter lab displays the code completion, however there is no way to actually use the completion. Hitting tab just inserts a tab (or 4 spaces)

**Comment by kevinzlu** [comment]
Can you go to options --> Keyboard Shortcuts --> search for inline-completion? It's likely that the default keybinding overrides are not working.

**Comment by hhuuggoo** [comment]
Oh wow - I had never looked at that before but I think the inline completer short cuts are just totally different than what I expected (what I need is shift + end) thanks!.

Just tried it out now but I'm getting 500s. I'm assuming Codeium is having an issue right now?

**Comment by hhuuggoo** [comment]
@kevinzlu I'm confirming that this works. for some reason on my Linux system, the shortcut is Alt + end for the completer.

**Comment by kevinzlu** [comment]
Thanks, I think there should be a way to override the default shortcuts, but I think that part could be broken.
